apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mi-historial-services
  namespace: demo
  labels:
    app: mi-historial-services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mi-historial-services
    spec:
      containers:
      - name: mi-historial-services
        image: resuelve/mi-historial-services:build-47-master
        ports:
        - containerPort: 80
        env:
        - name: LOGIN_URL
          value: "https://login.resuelve.io"
        - name: API_URL
          value: "http://localhost"
        - name: LOGIN_URL
          value: "https://login.sandbox.resuelve.io"
        - name: API_URL
          value: "https://mi-historial-services.sandbox.resuelve.io"
        - name: CC_URL
          value: https://mi-historial-services.sandbox.resuelve.io"
     imagePullSecrets:
      - name: reg-cred
      nodeSelector:
        cloud.google.com/gke-nodepool: "ingress-nginx"
